apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: aquashield-api-gateway
  labels:
    app.kubernetes.io/component: api-edge
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: http
      hostname: api.aquashield.example.com
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      hostname: api.aquashield.example.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: aquashield-api-tls
      allowedRoutes:
        namespaces:
          from: Same
