apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: notification-service-allow-http
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: notification-service
  action: ALLOW
  rules:
    - to:
        - operation:
            ports:
              - "8087"
            paths:
              - /api/alerts
              - /api/alerts/*
              - /actuator/health
              - /actuator/health/*
              - /actuator/info
              - /actuator/metrics
              - /actuator/metrics/*
    - to:
        - operation:
            ports:
              - "9096"
