apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: notification-service-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: notification-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: aquashield
      ports:
        - protocol: TCP
          port: 8087
