apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: analytics-service
  ports:
    - name: http
      port: 8090
      targetPort: http
