apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ingestion-service
  ports:
    - name: http
      port: 8084
      targetPort: http
    - name: grpc
      port: 9095
      targetPort: grpc
