apiVersion: v1
kind: Service
metadata:
  name: realtime-gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: realtime-gateway
  ports:
    - name: http
      port: 8088
      targetPort: http
