apiVersion: v1
kind: ConfigMap
metadata:
  name: managed-gcp-runtime
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  CLOUD_SQL_PRIVATE_IP: "10.128.1.3"
  MEMORYSTORE_REDIS_HOST: "10.128.0.3"
  REDIS_URL: "redis://10.128.0.3:6379"

  CLOUD_SQL_DATABASE_NAME: "aquashield"
  MEMORYSTORE_REDIS_PORT: "6379"
  PUBSUB_PROJECT_ID: "aerobic-guide-498413-u6"
  BIGTABLE_INSTANCE_ID: "aquashield-dev-telemetry"
  BIGTABLE_TABLE_NAME: "telemetry_readings"
  BIGQUERY_DATASET_ID: "aquashield_dev_analytics"
