apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-access-service
  annotations:
    iam.gke.io/gcp-service-account: aq-identity-dev@aquashield-ms-dev-20260808.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: project-service
  annotations:
    iam.gke.io/gcp-service-account: aq-project-dev@aquashield-ms-dev-20260808.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pond-service
  annotations:
    iam.gke.io/gcp-service-account: aq-pond-dev@aquashield-ms-dev-20260808.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensor-service
  annotations:
    iam.gke.io/gcp-service-account: aq-sensor-dev@aquashield-ms-dev-20260808.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingestion-service
  annotations:
    iam.gke.io/gcp-service-account: aq-ingestion-dev@aquashield-ms-dev-20260808.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  annotations:
    iam.gke.io/gcp-service-account: aq-notification-dev@aquashield-ms-dev-20260808.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: realtime-gateway
  annotations:
    iam.gke.io/gcp-service-account: aq-realtime-dev@aquashield-ms-dev-20260808.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  annotations:
    iam.gke.io/gcp-service-account: aq-analytics-dev@aquashield-ms-dev-20260808.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: audit-service
  annotations:
    iam.gke.io/gcp-service-account: aq-audit-dev@aquashield-ms-dev-20260808.iam.gserviceaccount.com
