apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: audit-service-allow-http
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: audit-service
  action: ALLOW
  rules:
    - to:
        - operation:
            ports:
              - "8092"
            paths:
              - /api/audit
              - /api/audit/*
              - /actuator/health
              - /actuator/health/*
              - /actuator/info
              - /actuator/metrics
              - /actuator/metrics/*
