apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml
  - authorization-policy.yaml

labels:
  - pairs:
      app.kubernetes.io/name: project-service
      app.kubernetes.io/component: project
    includeSelectors: true
