apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secrets
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/component: analytics
    app.kubernetes.io/part-of: aquashield
type: Opaque
stringData:
  # Public verification key only. The matching private signing key is not committed.
  JWT_PUBLIC_KEY_PEM: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtb4pI943aEBDo19HDDW2
    u5/GfBOBW23qTYn4gFJV0MTXIQtMqKy9ITLxGxnnm9m98EOM21XrtG0dENaq6xhN
    nhGW6mIWUVc949Ti8x36OlidnjcBG2ucwoE3yVdOBtt2SQ4ZTSW7hE5bwb6Dm9ne
    Rb/EjuvB1RqyJCs0nptqnxriOvJBOtuUB6HH/K4tcNr+oxMYpwybrAThWo3DMRw6
    8i2oY1OutbC7SIJhbgegLAVyh0uiMA32+FUnqAQYlQsAU+KhQsQ91Rj0HgH4kF7X
    e9fSXI2qyRlPBudOmAhr5hia+WizBy27NKyWrtXoxIzuroRUAIYwf3TxCHsMh6Y8
    HQIDAQAB
    -----END PUBLIC KEY-----
