apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/component: analytics
    app.kubernetes.io/part-of: aquashield
