apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: api-edge-proxy-http-health
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: api-edge-proxy
