apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: identity-access-service-http-health
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /actuator/health/readiness
  targetRef:
    group: ""
    kind: Service
    name: identity-access-service
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: project-service-http-health
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /actuator/health/readiness
  targetRef:
    group: ""
    kind: Service
    name: project-service
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: pond-service-http-health
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /actuator/health/readiness
  targetRef:
    group: ""
    kind: Service
    name: pond-service
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: sensor-service-http-health
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /actuator/health/readiness
  targetRef:
    group: ""
    kind: Service
    name: sensor-service
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: notification-service-http-health
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /actuator/health/readiness
  targetRef:
    group: ""
    kind: Service
    name: notification-service
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: realtime-gateway-http-health
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /actuator/health/readiness
  targetRef:
    group: ""
    kind: Service
    name: realtime-gateway
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: analytics-service-http-health
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: analytics-service
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: audit-service-http-health
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /actuator/health/readiness
  targetRef:
    group: ""
    kind: Service
    name: audit-service
