apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aquashield-dev

resources:
  - ../dev-managed
  - ../../base/edge
  - health-check-policies.yaml

labels:
  - pairs:
      app.kubernetes.io/edge-slice: public-http

patches:
  - target:
      kind: Gateway
      name: aquashield-api-gateway
    patch: |-
      - op: remove
        path: /spec/listeners/1
      - op: remove
        path: /spec/listeners/0/hostname
  - target:
      kind: HTTPRoute
      name: aquashield-api-routes
    patch: |-
      - op: replace
        path: /spec/parentRefs/0/sectionName
        value: http
      - op: remove
        path: /spec/hostnames
