apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aquashield-dev

resources:
  - ../dev-managed
  - ../../base/services/api-edge-proxy
  - ../../base/edge
  - health-check-policies.yaml

labels:
  - pairs:
      app.kubernetes.io/edge-slice: public-https

patches:
  - target:
      kind: Gateway
      name: aquashield-api-gateway
    patch: |-
      - op: add
        path: /spec/addresses
        value:
          - type: NamedAddress
            value: aquashield-dev-api-edge
      - op: replace
        path: /spec/listeners/0/hostname
        value: api.aquashield.live
      - op: replace
        path: /spec/listeners/1/hostname
        value: api.aquashield.live
      - op: remove
        path: /spec/listeners/1/tls/certificateRefs
      - op: add
        path: /spec/listeners/1/tls/options
        value:
          networking.gke.io/pre-shared-certs: aquashield-dev-api-edge
  - target:
      kind: HTTPRoute
      name: aquashield-api-routes
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: api.aquashield.live
      - op: replace
        path: /spec/rules
        value:
          - matches:
              - path:
                  type: PathPrefix
                  value: /api
            backendRefs:
              - group: ""
                kind: Service
                name: api-edge-proxy
                port: 8080
                weight: 1
          - matches:
              - path:
                  type: PathPrefix
                  value: /ws
            backendRefs:
              - group: ""
                kind: Service
                name: api-edge-proxy
                port: 8080
                weight: 1
  - target:
      kind: Deployment
      name: api-edge-proxy
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/app.kubernetes.io~1environment
        value: dev
  - target:
      kind: HTTPRoute
      name: aquashield-api-http-redirect
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: api.aquashield.live
