apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-access-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: project-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pond-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensor-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingestion-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: realtime-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: audit-service
