apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aquashield-dev

resources:
- namespace.yaml
- ../../base

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/environment: dev
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: add
      path: /spec/strategy
      value:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 0
          maxUnavailable: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 75m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 500m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 512Mi
  target:
    kind: Deployment
- patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 1
    - op: replace
      path: /spec/maxReplicas
      value: 1
  target:
    kind: HorizontalPodAutoscaler
images:
- name: analytics-service
  newName: asia-southeast1-docker.pkg.dev/aerobic-guide-498413-u6/analytics-service/analytics-service
  newTag: 783c78a16381
- name: audit-service
  newName: asia-southeast1-docker.pkg.dev/aerobic-guide-498413-u6/audit-service/audit-service
  newTag: 783c78a16381
- name: identity-access-service
  newName: asia-southeast1-docker.pkg.dev/aerobic-guide-498413-u6/identity-access-service/identity-access-service
  newTag: fa024d3554c0
- name: ingestion-service
  newName: asia-southeast1-docker.pkg.dev/aerobic-guide-498413-u6/ingestion-service/ingestion-service
  newTag: 783c78a16381
- name: notification-service
  newName: asia-southeast1-docker.pkg.dev/aerobic-guide-498413-u6/notification-service/notification-service
  newTag: 783c78a16381
- name: pond-service
  newName: asia-southeast1-docker.pkg.dev/aerobic-guide-498413-u6/pond-service/pond-service
  newTag: 783c78a16381
- name: project-service
  newName: asia-southeast1-docker.pkg.dev/aerobic-guide-498413-u6/project-service/project-service
  newTag: 783c78a16381
- name: realtime-gateway
  newName: asia-southeast1-docker.pkg.dev/aerobic-guide-498413-u6/realtime-gateway/realtime-gateway
  newTag: 783c78a16381
- name: sensor-service
  newName: asia-southeast1-docker.pkg.dev/aerobic-guide-498413-u6/sensor-service/sensor-service
  newTag: 783c78a16381
